# Generated by Django 5.1.2 on 2024-10-28 20:51

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=post.models.post_file_path
            ),
        ),
    ]
